class SaidNoError(Exception):
    pass

class SaidCancelError(Exception):
    pass
