#!/bin/bash
sudo python3 restartupdate.py
